# Generated by Django 4.0.3 on 2023-06-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_carddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='card_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='exp_month',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='exp_year',
            field=models.CharField(max_length=25),
        ),
    ]
