# Generated by Django 4.0.3 on 2023-06-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_carddetails_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
