# Generated by Django 4.0.3 on 2023-06-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_carddetails_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetails',
            old_name='card_id',
            new_name='id',
        ),
    ]
