# Generated by Django 4.0.3 on 2023-06-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_id_carddetails_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetails',
            name='otp',
        ),
    ]
