# Generated by Django 4.0.3 on 2023-06-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_carddetails_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
