# Generated by Django 4.0.3 on 2023-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_carddetails_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetails',
            old_name='card_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='otp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
