# Generated by Django 4.0.3 on 2023-06-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_card_id_carddetails_id_alter_carddetails_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetails',
            old_name='id',
            new_name='card_id',
        ),
    ]
