# Generated by Django 4.0.3 on 2023-06-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_id_carddetails_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pr_rv5',
            field=models.ImageField(default='', upload_to='polls/images'),
        ),
    ]
