# Generated by Django 4.1.7 on 2023-08-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_geoipconfig_remove_carddetails_otp_otpforcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='GeoIPConfig',
        ),
        migrations.RemoveField(
            model_name='otpforcard',
            name='card_details',
        ),
        migrations.DeleteModel(
            name='CardDetails',
        ),
        migrations.DeleteModel(
            name='OtpForCard',
        ),
    ]
